{% set name = "Orange3-Timeseries" %}
{% set version = "0.3.4" %}
{% set sha256 = "b35ef1b44f88fd62db2c0369b07784fcb1215cac91543987804b1820e583b686" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: True  # [py2k]

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - orange3
    - statsmodels >=0.6.1
    - pandas
    - numpy
    - scipy >=0.17

test:
  imports:
    - orangecontrib.timeseries

about:
  home: https://github.com/biolab/orange3-timeseries
  license: CC-BY-NC-3.0
  summary: 'Orange3 add-on for exploring time series and sequential data.'
  license_family: Other
  doc_url: http://orange3-timeseries.readthedocs.io
  dev_url: https://github.com/biolab/orange3-timeseries

extra:
  recipe-maintainers:
    - astaric
    - kernc
    - ajdapretnar
    - primozgodec
