{% set name = "Orange3-Timeseries" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 129fd975a8a13dc3580c55f7f5322c70ebf0ce2043c15133aa8bfce266434de1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - orange3
    - statsmodels >=0.10.0,<0.13.0
    - pandas
    - numpy
    - scipy >=0.17
    - more-itertools
    - python-dateutil

test:
  imports:
    - orangecontrib.timeseries

about:
  home: https://github.com/biolab/orange3-timeseries
  license: CC-BY-NC-3.0
  summary: Orange3 add-on for exploring time series and sequential data.
  license_family: Other
  doc_url: http://orange3-timeseries.readthedocs.io
  dev_url: https://github.com/biolab/orange3-timeseries

extra:
  recipe-maintainers:
    - astaric
    - ajdapretnar
    - primozgodec
    - markotoplak
