appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: bD9gD5/QJvf8wKCgqgYx8qHlX48l4J9uEDXqX6IZ3q1XGEWobkw61n3YVRmTncUqO2+sqeQTXP1K0/ZXTi1zEaLoZXS6aKOqyOR2VYN18dgrM+hdgMUSTXU4Mha9LIxPjv7kqVSOTPDp1zv6w+f3mdjoDOOTU7FK5c0uCfSvYRRViIZBxp6qF4caswn/Ntz+80/CFZuLh1jfi/tIFUg6ZZxCuJQlvH4EM4EUvq63iKm0Ky3mC+YpR7Ho8lfXvlVd97y5xw068kzgskZ3eA4cUC6sjmVXkSJyvUA3MPvdXr4H3xPX1LRtwlIN8Yrhwt/fBJ3TfTe2VbwUmeO72za5/K0QQh4IqK96tgFk6O8qylXuGOFD0k0tsJQbvwYRXXL2da355b9fX+HikvMslUlEboSltpGtYUDIQvoeirTez9FUhS4gcDHVQKIBHDLpizuj/YlK+AjR1dr7vSbtEu3Y97hcQFdIfBrXysi2gwpWjwVgWcfnoO8h4uHlHfDGbkitoXmJpNyWWHfBxKpyLN4AUhaIbVWqfq5ItBv0vdPwPDR18xg509x4J8KuB8oE9cpZdE+BAhqHzBeJ9XQJ8Fq3FrtfpKjgGlNgamo1khy3/3AaWC0LGInZxAoAEO8VyAlgRQaNIvYmRZh9uP9NMnvxF3IZk+Ak22CNQ3J7TghFbus=}
provider:
  win: azure
