travis:
  secure:
    BINSTAR_TOKEN: hOyrb+hHA+lqhTUls2ZSeBBs/lNb0jEqIN6h667CVWQ+ILIsNx33l6PTgwjSSufPA+O+mBvResICkOt3cZ8YRCMtnohU61A6gYuV46H5NX1hmCA4tabPG4N9Ijj2YJxu41Wh2YuNuT98BaGaON8COd7OQNvANRYmZ1WAcpiw0uydTClDDMRXvMZOYIPS7/JW8RfNNXLzuPqDGlnw7QaHeJR5tpmYJFNFF8WrLxZJy778SS2vy+g4GBQeIPvT6bFvNty6S/YoxNUOyOXD/dyFzjfp7/w3JJONKUqwPR8p5vpR191/pBYJgA210lckHvfGJuW/ZGR07K2OR4Cr1XTm4+9vkKanLNe3pC/hY1GnRBEFQibiLOHypD7Ulj3SkMFaZPnkLpdGMqJpAfosNz/kP0oe6gGInbn1D2DTFD3ASDnYe2AuyJY1cNYMWBdoJp0CU96dgrid8Q/Uza1iduZBi41EVDM3X/lTZnY4EsYzuFDDyPxBuFfvuFeYbdDLbKNqZmTHtkmML1NFpyKTaddHteCF2IVgE4p91Mi0k6QxgsexF5a7ADllpd3I9/glmxORab77OHJYldP3JGPn3MCQBjLQfyvN+yJ5l7I6gVvqAMNQT0Fnv3twZYUTx3VGvIkZmuM4wfPBxKeB0f4ZQpuk3E86NFxs/IAbwMungXkAAcM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
conda_forge_output_validation: true
